@startuml
title Диаграмма Пояснительной Модели IT News

actor "Читатель" as Reader
participant "UI (VUE.JS)" as UI
participant "BackEnd (Flask API)" as BackEnd
database "База данных\nPostgresql" as Database
participant "Искусственный Интеллект (AI)" as AI
participant "Парсер" as Parser


BackEnd -> Parser : (1) Запрашивает парсинг статей (через определенное время)
Parser --> BackEnd : (2) Отправляет спарсенные данные
BackEnd -> Database : (3) Сохраняет статьи в базе
Database --> BackEnd : (4) Подтверждение сохранения
BackEnd -> AI : (5) Запрашивает обработку статей
AI --> BackEnd : (6) Отправляет обработанные данные
BackEnd -> Database : (7) Сохраняет дополнительную информацию статьи в базе
Database --> BackEnd : (8) Подтверждение сохранения
Reader -> UI : (9) Запрашивает статьи
UI -> BackEnd : (10) Запрашивает данные
BackEnd -> Database : (11) Запрашивает актуальные статьи
Database --> BackEnd : (12) Отправляет данные
BackEnd --> UI : (13) Возвращает статьи
UI --> Reader : (14) Отображает статьи

note left of Reader
  Читатель - это конечный пользователь, который
  просматривает статьи.
end note

note right of AI
  Искусственный Интеллект обрабатывает статьи, создает
  краткие обзоры и категоризирует их.
end note

note right of Parser
  Парсер ответственен за сбор данных из веб-ресурсов и
  передачу данных в сервер Flask API.
end note

@enduml
